version: '3.1'

services:
  mysql:
    build:
      context: ./mysql
    image: bcandido/artifactory-poc/mysql
    restart: always
    networks:
      default:
        aliases:
          - mysql
    environment:
      - MYSQL_DATABASE=artdb
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=artifactory
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=artifactory

  artifactory:
    build:
      context: ./artifactory
    image: bcandido/artifactory-poc/artifactory
    restart: always
    ports:
      - 8081:8081
    networks:
      default:
        aliases:
          - artifactory
    depends_on:
      - mysql
      
networks:
  default:
